version: "3.7"
services:
  server-front:
    build:
      context: .
    image: ovloop-front
    volumes:
      - ./src:/app/src
      - ./server:/app/server
    container_name: ovloop-front-dev
    environment: 
      NODE_ENV: local
      API_HOST: backend
      API_PORT: 8080
    ports:
      - 7777:7777
    external_links:
      - ovloop-api-dev:backend
    networks: 
      - default
      - ovloop-app
    entrypoint: ["npm", "run", "dev"]
networks:
  default:
    name: front-network
  ovloop-app:
    external: true



