version: "3.7"
services:
  server-front:
    build:
      context: .
    image: ovloop-front
    volumes:
      - ./src:/app/src
      - ./server:/app/server
    container_name: ovloop-front-dev
    ports:
      - 7777:7777
    # depends_on:
      # - mongo
    # environment:
    #   PORT: 7777
    entrypoint: ["npm", "run", "dev"]
  # mongo:
  #   container_name: mongo_dashboard
  #   image: mongo
  #   ports:
  #     - "27017:27017"
networks:
  default:
    external:
      name: ovloop-app

